title: Dog Trainer ATX
baseURL: /
params:
  footer:
    content: '&copy;  All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: ''
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest training tips
    subscribe_title: Subscribe
    tagline: Dog Trainer ATX
  header:
    has_nav: true
    logo_img: ''
    title: Dog Trainer ATX
    menu:
      actions:
        - label: Sign Up
          url: /signup
  palette: purple
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
